version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hk123

  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node

  hk-s3:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: HK-MINIO
      MINIO_ROOT_PASSWORD: HK-MINIO-PASS
    command: server /data
